# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ProjectHemera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectHemera
  pod 'Firebase/Core', '~> 5.3.0'

  target 'ProjectHemeraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ProjectHemera-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectHemera-tvOS

  target 'ProjectHemera-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
